#include <complex>

std::vector<std::complex<float> > dft_16(float* input) {
  std::vector<std::complex<float> > output(16);
  const float kWeight0 = 0.000000e+00;
  const float kWeight1 = 1.000000e+00;
  const float kWeight2 = 7.071068e-01;
  const float kWeight3 = 9.238795e-01;
  const float kWeight4 = 3.826834e-01;
  const std::complex<float> w0 = input[0]  + input[8] ;
  const std::complex<float> w1 = input[0]  + -input[8] ;
  const std::complex<float> w2 = input[4]  + input[12] ;
  const std::complex<float> w3 = input[4]  + -input[12] ;
  const std::complex<float> w4 = w0  + w2 ;
  const std::complex<float> w5 = w0  + -w2 ;
  const std::complex<float> w6 = w1  +  std::complex<float>( kWeight0, -kWeight1) * w3;
  const std::complex<float> w7 = w1  +  std::complex<float>( kWeight0,  kWeight1) * w3;
  const std::complex<float> w8 = input[2]  + input[10] ;
  const std::complex<float> w9 = input[2]  + -input[10] ;
  const std::complex<float> w10 = input[6]  + input[14] ;
  const std::complex<float> w11 = input[6]  + -input[14] ;
  const std::complex<float> w12 = w8  + w10 ;
  const std::complex<float> w13 = w8  + -w10 ;
  const std::complex<float> w14 = w9  +  std::complex<float>( kWeight0, -kWeight1) * w11;
  const std::complex<float> w15 = w9  +  std::complex<float>( kWeight0,  kWeight1) * w11;
  const std::complex<float> w16 = w4  + w12 ;
  const std::complex<float> w17 = w4  + -w12 ;
  const std::complex<float> w18 = w6  +  std::complex<float>( kWeight2, -kWeight2) * w14;
  const std::complex<float> w19 = w6  +  std::complex<float>(-kWeight2,  kWeight2) * w14;
  const std::complex<float> w20 = w5  +  std::complex<float>( kWeight0, -kWeight1) * w13;
  const std::complex<float> w21 = w5  +  std::complex<float>( kWeight0,  kWeight1) * w13;
  const std::complex<float> w22 = w7  +  std::complex<float>(-kWeight2, -kWeight2) * w15;
  const std::complex<float> w23 = w7  +  std::complex<float>( kWeight2,  kWeight2) * w15;
  const std::complex<float> w24 = input[1]  + input[9] ;
  const std::complex<float> w25 = input[1]  + -input[9] ;
  const std::complex<float> w26 = input[5]  + input[13] ;
  const std::complex<float> w27 = input[5]  + -input[13] ;
  const std::complex<float> w28 = w24  + w26 ;
  const std::complex<float> w29 = w24  + -w26 ;
  const std::complex<float> w30 = w25  +  std::complex<float>( kWeight0, -kWeight1) * w27;
  const std::complex<float> w31 = w25  +  std::complex<float>( kWeight0,  kWeight1) * w27;
  const std::complex<float> w32 = input[3]  + input[11] ;
  const std::complex<float> w33 = input[3]  + -input[11] ;
  const std::complex<float> w34 = input[7]  + input[15] ;
  const std::complex<float> w35 = input[7]  + -input[15] ;
  const std::complex<float> w36 = w32  + w34 ;
  const std::complex<float> w37 = w32  + -w34 ;
  const std::complex<float> w38 = w33  +  std::complex<float>( kWeight0, -kWeight1) * w35;
  const std::complex<float> w39 = w33  +  std::complex<float>( kWeight0,  kWeight1) * w35;
  const std::complex<float> w40 = w28  + w36 ;
  const std::complex<float> w41 = w28  + -w36 ;
  const std::complex<float> w42 = w30  +  std::complex<float>( kWeight2, -kWeight2) * w38;
  const std::complex<float> w43 = w30  +  std::complex<float>(-kWeight2,  kWeight2) * w38;
  const std::complex<float> w44 = w29  +  std::complex<float>( kWeight0, -kWeight1) * w37;
  const std::complex<float> w45 = w29  +  std::complex<float>( kWeight0,  kWeight1) * w37;
  const std::complex<float> w46 = w31  +  std::complex<float>(-kWeight2, -kWeight2) * w39;
  const std::complex<float> w47 = w31  +  std::complex<float>( kWeight2,  kWeight2) * w39;
  output[0] = w16  + w40 ;
  output[8] = w16  + -w40 ;
  output[1] = w18  +  std::complex<float>( kWeight3, -kWeight4) * w42;
  output[9] = w18  +  std::complex<float>(-kWeight3,  kWeight4) * w42;
  output[2] = w20  +  std::complex<float>( kWeight2, -kWeight2) * w44;
  output[10] = w20  +  std::complex<float>(-kWeight2,  kWeight2) * w44;
  output[3] = w22  +  std::complex<float>( kWeight4, -kWeight3) * w46;
  output[11] = w22  +  std::complex<float>(-kWeight4,  kWeight3) * w46;
  output[4] = w17  +  std::complex<float>( kWeight0, -kWeight1) * w41;
  output[12] = w17  +  std::complex<float>( kWeight0,  kWeight1) * w41;
  output[5] = w19  +  std::complex<float>(-kWeight4, -kWeight3) * w43;
  output[13] = w19  +  std::complex<float>( kWeight4,  kWeight3) * w43;
  output[6] = w21  +  std::complex<float>(-kWeight2, -kWeight2) * w45;
  output[14] = w21  +  std::complex<float>( kWeight2,  kWeight2) * w45;
  output[7] = w23  +  std::complex<float>(-kWeight3, -kWeight4) * w47;
  output[15] = w23  +  std::complex<float>( kWeight3,  kWeight4) * w47;

  return output;
}
